name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  set_gh_pages:
    name: Build and Set gh-pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: run anmaped/rmtld3synth image
        run: |
          docker run --rm \
          --entrypoint /bin/bash \
          -v ${PWD}:/workspace/source:z  \
          docker.io/anmaped/rmtld3synth:v0.6-x \
          -c 'cp -r /workspace/source /localsource && cd /localsource && \
          eval $(opam env) && \
          ./configure --js_of_ocaml --without-z3-solver && make js && \
          mkdir -p /workspace/source/public && \
          cp _build/default/src/rmtld3synth.js /workspace/source/public &&
          cp doc/page/index.html /workspace/source/public &&
          cp doc/page/style.css /workspace/source/public &&
          ls /workspace/source/public -l'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public