name: Web Build

on:
  - push
  - pull_request

permissions: read-all

jobs:
  set_gh_pages:
    name: Build web
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: run anmaped/rmtld3synth image
        run: |
          docker run --rm \
          --entrypoint /bin/bash \
          -v ${PWD}:/workspace/source:z  \
          docker.io/anmaped/rmtld3synth:v0.6-x \
          -c 'cp -r /workspace/source /localsource && cd /localsource && \
          eval $(opam env) && \
          ./configure --js_of_ocaml --without-z3-solver && make js && \
          mkdir -p /workspace/source/public && \
          cp _build/default/src/rmtld3synth.js /workspace/source/public

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-artifact-${{ github.sha }}
          path: _build/default/src/rmtld3synth.js
